[[redirects]]
  from = "/acl/*"
  to = "http://39.98.123.211:8170/admin"
  status = 200
  force = true

[[redirects]]
  from = "/acl/*"
  to = "http://39.98.123.211:8170"
  status = 200
  force = true

[[redirects]]
  from = "/admin/production/*"
  to = "http://39.98.123.211:8510"
  status = 200
  force = true

[[redirects]]
  from = "/product/*"
  to = "http://39.98.123.211:8510/admin"
  status = 200
  force = true

